### PR TITLE
Development

### PR DESCRIPTION
**Pull request by i4seeu**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, good job. Kindly remove unnecessary comments and `puts`.
Also, update `bubble_sort_by` so that it should work without block. Once fixed, kindly resubmit for review.

**Comment by i4seeu** [comment]
Hello, I thought the project said it should work with a block? i am confused now

**Comment by i4seeu** [comment]
or you just want the code to accept anything that people throw at it?

**Review by inhaq — APPROVED** [review]
It's 👍🏻, Good job. Go ahead and submit your project completion form.
Good luck with the next project.

**Pull request merged**
